name: Instrumented Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  AVD_NAME: WearOS_CI
  API_LEVEL: 30

jobs:
  instrumented-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        
    - name: Cache AVD
      uses: actions/cache@v3
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ env.API_LEVEL }}-${{ env.AVD_NAME }}
        
    - name: Create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ env.API_LEVEL }}
        target: google_apis
        arch: x86_64
        profile: wear_round
        avd-name: ${{ env.AVD_NAME }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: echo "Generated AVD snapshot for caching."
        
    - name: Run instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ env.API_LEVEL }}
        target: google_apis
        arch: x86_64
        profile: wear_round
        avd-name: ${{ env.AVD_NAME }}
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: |
          ./gradlew connectedDebugAndroidTest --stacktrace
          ./gradlew createDebugCoverageReport
          
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          app/build/reports/androidTests/
          app/build/reports/coverage/
          app/build/test-results/
          
    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v3
      with:
        files: app/build/reports/coverage/androidTest/debug/report.xml
        name: instrumented-tests
        flags: instrumented
        
    - name: Comment PR with coverage
      if: github.event_name == 'pull_request' && always()
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: app/build/reports/coverage/androidTest/debug/report.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 25
        min-coverage-changed-files: 60
        title: 📊 Instrumented Test Coverage Report